import StudentModel from "./StudentModel";

let studentModels = [
  {
    name: "Israel Israeli1",
    age: 18,
    gender: "M",
    school: "UHIS",
    email: "Israel.Israeli1@gmail.com",
    graduated: true,
  },
  {
    name: "Israel Israeli2",
    age: 19,
    gender: "F",
    school: "UHIS",
    email: "Israel.Israeli2@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli3",
    age: 20,
    gender: "M",
    school: "UHIS",
    email: "Israel.Israeli3@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli4",
    age: 21,
    gender: "F",
    school: "Tel-Hai",
    email: "Israel.Israeli4@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli5",
    age: 22,
    gender: "M",
    school: "Tel-Hai",
    email: "Israel.Israeli5@gmail.com",
    graduated: true,
  },
  {
    name: "Israel Israeli6",
    age: 23,
    gender: "F",
    school: "UHIS",
    email: "Israel.Israeli6@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli7",
    age: 24,
    gender: "M",
    school: "HUJI",
    email: "Israel.Israeli7@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli8",
    age: 25,
    gender: "F",
    school: "TOP",
    email: "Israel.Israeli8@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli9",
    age: 26,
    gender: "M",
    school: "TOP",
    email: "Israel.Israeli9@gmail.com",
    graduated: true,
  },
  {
    name: "Israel Israeli10",
    age: 27,
    gender: "F",
    school: "TOP",
    email: "Israel.Israeli10@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli11",
    age: 28,
    gender: "M",
    school: "HUJI",
    email: "Israel.Israeli11@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli12",
    age: 29,
    gender: "F",
    school: "HUJI",
    email: "Israel.Israeli12@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli13",
    age: 30,
    gender: "M",
    school: "UHIS",
    email: "Israel.Israeli13@gmail.com",
    graduated: true,
  },
  {
    name: "Israel Israeli14",
    age: 31,
    gender: "F",
    school: "HUJI",
    email: "Israel.Israeli14@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli15",
    age: 32,
    gender: "M",
    school: "TOP",
    email: "Israel.Israeli15@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli16",
    age: 33,
    gender: "F",
    school: "BGU",
    email: "Israel.Israeli16@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli17",
    age: 34,
    gender: "M",
    school: "Tel-Hai",
    email: "Israel.Israeli17@gmail.com",
    graduated: true,
  },
  {
    name: "Israel Israeli18",
    age: 35,
    gender: "F",
    school: "BGU",
    email: "Israel.Israeli18@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli19",
    age: 36,
    gender: "M",
    school: "Tel-Hai",
    email: "Israel.Israeli19@gmail.com",
    graduated: false,
  },
  {
    name: "Israel Israeli20",
    age: 37,
    gender: "F",
    school: "BGU",
    email: "Israel.Israeli20@gmail.com",
    graduated: false,
  },
];

const students: StudentModel[] = [];
studentModels.forEach((studentModel) => {
  let { name, age, gender, school, email, graduated } = studentModel;
  students.push(new StudentModel(name, age, gender, school, email, graduated));
});

export default students;
