import StudentModel from "./StudentModel";

let studentModels = [
  {
    name: "Israel Israeli1",
    age: 18,
    school: "UHIS",
    email: "Israel.Israeli1@gmail.com",
    graduated: true,
    id: "045814121",
  },
  {
    name: "Israel Israeli2",
    age: 19,
    school: "UHIS",
    email: "Israel.Israeli2@gmail.com",
    graduated: false,
    id: "175594759",
  },
  {
    name: "Israel Israeli3",
    age: 20,
    school: "UHIS",
    email: "Israel.Israeli3@gmail.com",
    graduated: false,
    id: "209448065",
  },
  {
    name: "Israel Israeli4",
    age: 21,
    school: "Tel-Hai",
    email: "Israel.Israeli4@gmail.com",
    graduated: false,
    id: "357764915",
  },
  {
    name: "Israel Israeli5",
    age: 22,
    school: "Tel-Hai",
    email: "Israel.Israeli5@gmail.com",
    graduated: true,
    id: "433193835",
  },
  {
    name: "Israel Israeli6",
    age: 23,
    school: "UHIS",
    email: "Israel.Israeli6@gmail.com",
    graduated: false,
    id: "568579458",
  },
  {
    name: "Israel Israeli7",
    age: 24,
    school: "HUJI",
    email: "Israel.Israeli7@gmail.com",
    graduated: false,
    id: "699893682",
  },
  {
    name: "Israel Israeli8",
    age: 25,
    school: "TOP",
    email: "Israel.Israeli8@gmail.com",
    graduated: false,
    id: "746559089",
  },
  {
    name: "Israel Israeli9",
    age: 26,
    school: "TOP",
    email: "Israel.Israeli9@gmail.com",
    graduated: true,
    id: "847699657",
  },
  {
    name: "Israel Israeli10",
    age: 27,
    school: "TOP",
    email: "Israel.Israeli10@gmail.com",
    graduated: false,
    id: "912398577",
  },
  {
    name: "Israel Israeli11",
    age: 28,
    school: "HUJI",
    email: "Israel.Israeli11@gmail.com",
    graduated: false,
    id: "048958909",
  },
  {
    name: "Israel Israeli12",
    age: 29,
    school: "HUJI",
    email: "Israel.Israeli12@gmail.com",
    graduated: false,
    id: "156253516",
  },
  {
    name: "Israel Israeli13",
    age: 30,
    school: "UHIS",
    email: "Israel.Israeli13@gmail.com",
    graduated: true,
    id: "284831803",
  },
  {
    name: "Israel Israeli14",
    age: 31,
    school: "HUJI",
    email: "Israel.Israeli14@gmail.com",
    graduated: false,
    id: "336048896",
  },
  {
    name: "Israel Israeli15",
    age: 32,
    gender: "M",
    school: "TOP",
    email: "Israel.Israeli15@gmail.com",
    graduated: false,
    id: "491614717",
  },
  {
    name: "Israel Israeli16",
    age: 33,
    school: "BGU",
    email: "Israel.Israeli16@gmail.com",
    graduated: false,
    id: "521463556",
  },
  {
    name: "Israel Israeli17",
    age: 34,
    school: "Tel-Hai",
    email: "Israel.Israeli17@gmail.com",
    graduated: true,
    id: "693400882",
  },
  {
    name: "Israel Israeli18",
    age: 35,
    school: "BGU",
    email: "Israel.Israeli18@gmail.com",
    graduated: false,
    id: "794124674",
  },
  {
    name: "Israel Israeli19",
    age: 36,
    school: "Tel-Hai",
    email: "Israel.Israeli19@gmail.com",
    graduated: false,
    id: "865148875",
  },
  {
    name: "Israel Israeli20",
    age: 37,
    school: "BGU",
    email: "Israel.Israeli20@gmail.com",
    graduated: false,
    id: "910992977",
  },
];
const students: StudentModel[] = [];
studentModels.forEach((studentModel) => {
  let { name, age, school, email, graduated, id } = studentModel;
  students.push({name, age, school, email, graduated, id});
});

export default students;
